faster backtest
idkravitz/binance-trade-bot pull request #4
Opened 2021-05-26 18:00 UTC by Mila432

replaced sqlitedict with diskcache and added bulk data download instead of using api for old data

2021-05-26 20:26 UTC, tntwist commented
Hi getting the following error:
```
ModuleNotFoundError: No module named 'xmltodict'
```

My linter shows xmltodict and diskcache as missing. Did you forget to add it to the requirements?

2021-05-26 20:50 UTC, tntwist commented
Installed the deps myself and it works like a charm 🎉

2021-05-27 15:51 UTC, vitorverasm commented
Better to add dependencies to `requirements.txt`:
```txt
xmltodict==0.12.0
diskcache==5.2.1
```

2021-05-27 15:54 UTC, vitorverasm requested changes
This works well! 🥳 

Just add dependencies to `requirements.txt`:
```txt
xmltodict==0.12.0
diskcache==5.2.1
```

2021-05-31 05:26 UTC, idkravitz commented
Hi, please check the lint errors highlighted in workflow and fix them

2021-05-31 05:33 UTC, idkravitz commented on binance_trade_bot/backtest.py
> +            f'https://s3-ap-northeast-1.amazonaws.com/data.binance.vision?delimiter=/&prefix=data/spot/{frame}/klines/{ticker_symbol}/{interval}/',
Why not using [params argument](https://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls)?

2021-06-10 13:52 UTC, closed without merging